trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'azure-midas-connection'
  webAppName: 'midas-net'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet restore Midas.API/Midas.API.csproj
  displayName: 'Restaurar dependências'

- script: dotnet build Midas.API/Midas.API.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build do projeto'

- script: dotnet publish Midas.API/Midas.API.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publicar aplicação'

- task: AzureWebApp@1
  displayName: 'Deploy no Azure Web App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)'