trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet restore Midas.csproj
  displayName: 'Restaurar dependências'

- script: dotnet build Midas.csproj --configuration $(buildConfiguration)
  displayName: 'Build do projeto'

- script: dotnet test Midas.csproj --configuration $(buildConfiguration) --no-build
  displayName: 'Executar testes'